version: "3.5"
services:
  # entrypoint http://
  traefik:
    image: traefik:2.4
    networks:
      traefik-network:
    environment:
      # https://doc.traefik.io/traefik/v2.3/reference/static-configuration/env/
      TRAEFIK_ENTRYPOINTS_web_ADDRESS: :80
      TRAEFIK_PROVIDERS_HTTP_ENDPOINT: http://httpd/${OS_CONTAINER}/${OS_OBJECT}
      TRAEFIK_PROVIDERS_HTTP_POLLINTERVAL: 15
      TRAEFIK_PROVIDERS_HTTP_POLLTIMEOUT: 15
      TRAEFIK_LOG_LEVEL: ${TRAEFIK_LOG_LEVEL:-ERROR}
    ports:
      - "80:80"
      - "8082:80"

  # dynamic config
  httpd:
    image: nginx:latest
    networks:
      traefik-network:
    volumes:
      # - ./dynamic_conf.json:/usr/share/nginx/html/dynamic_conf.json
      # use templating nginx file (>=1.19)
      - ./nginx-dynamic_conf.template:/etc/nginx/templates/default.conf.template
    environment:
      # Openstack Swift URL
      - OS_STORAGE_URL=${OS_STORAGE_URL:? OS_STORAGE_URL not defined}
      - OS_CONTAINER=${OS_CONTAINER:? OS_CONTAINER not defined}
      - OS_OBJECT=${OS_OBJECT:? OS_OBJECT not defined}

networks:
  traefik-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

#  # backend
#  whoami1:
#    image: containous/whoami
#  whoami2:
#    image: containous/whoami
#

