version: "3.8"
services:
  # entrypoint http://
  traefik:
    image: traefik:2.4
    environment:
      TRAEFIK_ENTRYPOINTS_web_ADDRESS: :80
      TRAEFIK_PROVIDERS_HTTP_ENDPOINT: http://httpd/dynamic_conf.json
    ports:
      - "80:80"

  # dynamic config
  httpd:
    image: nginx:latest
    volumes:
      - ./dynamic_conf.json:/usr/share/nginx/html/dynamic_conf.json

  # backend
  whoami1:
    image: containous/whoami
  whoami2:
    image: containous/whoami


